### ISSUE TITLE
Events not editable through netlify properly

### ISSUE THREAD

**Issue by ghoshbishakh** [lugnitdgp/lugnitdgp.github.io#38]

**Comment by Compro-Prasad** [comment]
What is the problem?

**Comment by ghoshbishakh** [comment]
Description does not get updated

**Comment by Compro-Prasad** [comment]
Check it again. I fixed it long ago.

**Comment by ankan17** [comment]
@ghoshbishakh Is the problem still there? If not, please close this issue.

**Comment by ghoshbishakh** [comment]
No!

1. User must upload a new thumb every time
2. Even after uploading a new thumb one has to change the photo url
3. And even after everything.. the description is not updated.

**Comment by ankan17** [comment]
What solutions do you propose to problems 1 and 2? @ghoshbishakh

**Comment by ghoshbishakh** [comment]
@Compro-Prasad please.. clarify and help

**Comment by ankan17** [comment]
only 1 seems to be the problem.. Because I could update the description of an event without changing photo url.. but had t upload the thumb once again

**Comment by ghoshbishakh** [comment]
and we need to manually set the url which is a problem

**Comment by ghoshbishakh** [comment]
? is it really solved?

**Comment by ankan17** [comment]
Netlify is not very consistent with datetime widget. Built a workaround. See 9d20ded9722c5e407b682d0412405a20df9bab5e

**Comment by ankan17** [comment]
Closing through 9d20ded9722c5e407b682d0412405a20df9bab5e
